version: '3.3'
services:
  app:
    image: api-spring
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgbls
      